### ISSUE TITLE
Metadata `SkipJsonSchema` ignored when constructing click options from model

### ISSUE THREAD

**Issue by mgiammar** [felix-martel/pydanclick#42]
First off, thanks for working on this extremely useful package! I've been trying to integrate it to reduce boilerplate necessary for creating CLI programs for some complex models.

## Observed Behavior

I've run into the following issue using pydanclick where I've defined a field (for an large, intermediate tensor) in my model which is not seralized in the JSON or the JSON schema using the following type annotation,

```
large_tensor = SkipJsonSchema[Annotated[torch.Tensor, Field(default=None, exclude=True)]]
```

which works as expected with pydantic (not in `model_dump()` or `model_json_schema()`), but when I try to create click options from a model, I get the following error:

### Traceback
```
python pydanclick_error.py --help
Traceback (most recent call last):
  File "/opt/miniconda3/envs/ttsim3d-dev/lib/python3.12/site-packages/pydantic/type_adapter.py", line 270, in _init_core_attrs
    self._core_schema = _getattr_no_parents(self._type, '__pydantic_core_schema__')
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ttsim3d-dev/lib/python3.12/site-packages/pydantic/type_adapter.py", line 112, in _getattr_no_parents
    raise AttributeError(attribute)
AttributeError: __pydantic_core_schema__

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mgiammar/Documents/ttsim3d/pydanclick_error.py", line 43, in <module>
    @from_pydantic(MyModel)
     ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ttsim3d-dev/lib/python3.12/site-packages/pydanclick/main.py", line 51, in from_pydantic
    options, validator = convert_to_click(
                         ^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ttsim3d-dev/lib/python3.12/site-packages/pydanclick/model/model_conversion.py", line 72, in convert_to_click
    qualified_names, options = convert_fields_to_options(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ttsim3d-dev/lib/python3.12/site-packages/pydanclick/model/field_conversion.py", line 49, in convert_fields_to_options
    option = _get_option_from_field(
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ttsim3d-dev/lib/python3.12/site-packages/pydanclick/model/field_conversion.py", line 161, in _get_option_from_field
    "type": _get_type_from_field(field_info),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ttsim3d-dev/lib/python3.12/site-packages/pydanclick/model/type_conversion.py", line 148, in _get_type_from_field
    return _get_pydanclick_type(_get_click_type_from_field(field))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ttsim3d-dev/lib/python3.12/site-packages/pydanclick/model/type_conversion.py", line 194, in _get_click_type_from_field
    return _create_custom_type(field)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ttsim3d-dev/lib/python3.12/site-packages/pydanclick/model/type_conversion.py", line 200, in _create_custom_type
    type_adapter = TypeAdapter(cast(Type[Any], field.annotation))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ttsim3d-dev/lib/python3.12/site-packages/pydantic/type_adapter.py", line 257, in __init__
    self._init_core_attrs(rebuild_mocks=False)
  File "/opt/miniconda3/envs/ttsim3d-dev/lib/python3.12/site-packages/pydantic/type_adapter.py", line 135, in wrapped
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ttsim3d-dev/lib/python3.12/site-packages/pydantic/type_adapter.py", line 277, in _init_core_attrs
    self._core_schema = _get_schema(self._type, config_wrapper, parent_depth=self._parent_depth)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ttsim3d-dev/lib/python3.12/site-packages/pydantic/type_adapter.py", line 95, in _get_schema
    schema = gen.generate_schema(type_)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ttsim3d-dev/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 655, in generate_schema
    schema = self._generate_schema_inner(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ttsim3d-dev/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 929, in _generate_schema_inner
    return self.match_type(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ttsim3d-dev/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 1038, in match_type
    return self._unknown_type_schema(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ttsim3d-dev/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 558, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'torch.Tensor'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.9/u/schema-for-unknown-type
```

Traversing through a debugger, I see that the parser correctly picks up the `SkipJsonSchema` metadata for the field, but this metadata is unused during the logic for choosing if a field should be included as a click option.
Below is a minimally working piece of code that replicates this error:

### Minimally working example
```
"""Minimally working example of pydanclick error."""

import torch
import click

from typing import Annotated
from pydantic import BaseModel, ConfigDict, Field
from pydantic.json_schema import SkipJsonSchema
from pydanclick import from_pydantic


class MyModel(BaseModel):
    """Some example model.

    Attributes
    ----------
    input_param : float
        Some input parameter. Should be a CLI input
    some_tensor : torch.Tensor
        Some tensor that should not be serialized or an input
    """

    model_config = ConfigDict(arbitrary_types_allowed=True)

    # This should be a model input
    input_param: float = 1.23

    # Not a model input, and should not be serialized.
    some_tensor: SkipJsonSchema[
        Annotated[torch.Tensor, Field(default=None, exclude=True)]
    ]

    def __init__(self, **data):
        super().__init__(**data)

    def do_something(self):
        """Some method that does something."""
        # populate some_tensor...
        return self.input_param * 2


@click.command()
@from_pydantic(MyModel)
def main(params: MyModel):
    """Main function."""
    my_model = MyModel(**params.dict())
    my_model.do_something()


if __name__ == "__main__":
    main()
```

## Expected Behavior

The schema-excluded tensor field is gracefully skipped by pydanclick when generating the CLI inputs from a model.

I know there are easy workarounds to create a working CLI program still using the same model object (e.g. creating a CLI wrapper class or not using pydanclick and reverting to click options), but my objective here is to expose easy-to-use programs to users while maintaining underlying, complex functionality of Python classes hence the storage of intermediary results.
However, it would be great to have pydanclick *just work* to reduce overall maintenance costs of the codebase(s) as things get modified/updated.

**Comment by felix-martel** [comment]
Thanks for the bug report and investigation! Pydanclick definitely shouldn't fail on this case, however I'm not sure the field should be automatically excluded from the CLI just because it's annotated with `SkipJsonSchema` or with `Field(exclude=True)` (I'm not sure the point of  `SkipJsonSchema` is used in the wild tbh – can we assume that skipped fields are somehow "private" and thus excluded from external interfaces? if so, it would make sense to exclude them).

However, you can use the built-in **exclude** option: `@from_pydantic(MyModel, exclude=["some_tensor"])` and `some_tensor` won't be added to Click (see [API Reference](https://felix-martel.github.io/pydanclick/api_reference/)). Does that fit your use case? When I finally merge #14, you'll even be able to add this directly to your model or your field, so that `some_tensor` is excluded from all CLIs that use `MyModel`.

I'll try to come up with a fix for `SkipJsonSchema` annotation.

**Comment by mgiammar** [comment]
Likewise I'm not familiar with the uses of `SkipJsonSchema`, but using `Field(exclude=True)` is sufficient for my use case. I added `SkipJsonSchema` after seeing the `PydanticSchemaGenerationError` to check if that was the issue.

In my albeit limited understanding of `SkipJsonSchema`, it's annotation is used to exclude an attribute/field from a JSON schema for defining a language-independent model ([pydantic docs on this](https://docs.pydantic.dev/latest/concepts/json_schema/#generating-json-schema)). I think its safe to say these attributes/fields are not exposed or guaranteed to exist so should be excluded from arguments.

The built-in exclude option works for my case. Thanks for the quick response and helpful suggestions!
